#!/usr/bin/bash

#rm -rf ~/Marlin/Marlin/.pio

cp MarlinConfig/Configuration* ../Marlin/Marlin/

#sed -i 's/default_envs = mega2560/default_envs = STM32F103RET6_creality/' ../Marlin/platformio.ini

diff ./DWIN_SET/ ../Configurations/config/examples/Creality/Ender-3\ V2/LCD\ Files/DWIN_SET/ && echo "DWIN data unchanged"
